### ISSUE TITLE
Thanks and a Question

### ISSUE THREAD

**Issue by benlieb** [farfanoide/inflector.vim#2]
Thanks for this plugin, I'm not sure why there isn't anything else like it. I'll use this every day.

My question is this. You say "This might at some point become a real plugin", but it seems pretty functional as-is. Is there something I'm missing?

**Comment by farfanoide** [comment]
this was a pet project for me to learn vimscript and i couldnt give it the time it needs. it still lacks support for vim-repeat which seems quite important to me but at least it works.
i use it every day and it suits my needs ok, however i'd like to improve the rudimentary conversions it has at some point.

**Comment by benlieb** [comment]
Yes vim-repeat support would be useful. I hadn't tried it yet. I'll follow the project and look forward to any improvements you make!

**Comment by benlieb** [comment]
Just circling back to this to see if there is repeat support. Do you know what that would actually entail? I've never written much Vimscript, but I might be open to collaborating or giving it a shot. I might need to be pointed in the right direction though.

**Comment by farfanoide** [comment]
hi @benlieb, sadly no, havent had time to get on it and its a feature i'd like more and more so if you want to give it a try i think the general idea is to encapsulate the plugin call in a function that can be called by repeat-vim like so:

`
silent! call repeat#set("\<Plug>InflectText", v:count)
`

i reckon you'd also have to save the last inflection used in a local variable to the script.

let me know how it goes, i greatly appreciate any effort you put into this.

cheers
