### ISSUE TITLE
Conflicts with `clipboard=unnamed`

### ISSUE THREAD

**Issue by Kache** [farfanoide/inflector.vim#3]
Just discovered this plugin, but wasn't able to get it to function. Is it still working for you?

**Comment by farfanoide** [comment]
hi @Kache , yes i still use it on neovim v 0.7.2 although i know there are more robust options out there.
i havent tested it but if you're using neovim maybe this works better for you: https://github.com/johmsalas/text-case.nvim

let me know the steps you did to install it and maybe we can debug what went wrong

**Comment by Kache** [comment]
Oh, is it nvim only? I'm on vim. ~~I'll give the other one a try too.~~ That other one looks definitely nvim only with the lua.

**Comment by farfanoide** [comment]
if you are on vim this one should work, you just need to follow the installation instructions which is basically add the mapping you want (this is required if you want the plugin to automatically create mappings for you):
```vim
let g:inflector_mapping = 'gI'
```
and then install with your plugin manager, note the mapping should go BEFORE the plugin installation. let me know if this helps you

**Comment by Kache** [comment]
I don't know vimscript well, but debugged this plugin a bit and found issues with its register pasting. I was able to get it working by inputting `l:result` directly:

```diff
diff --git i/plugin/inflector.vim w/plugin/inflector.vim
index 0c3e603..d1f1c55 100644
--- i/plugin/inflector.vim
+++ w/plugin/inflector.vim
@@ -92,11 +92,8 @@ function! s:Inflect(type, ...)
     echom 'Select Inflection (' . join(keys(l:inflections)) . '):'
     let l:inflection = nr2char(getchar())

-    " return early on invalid inflection
-    if ! has_key(l:inflections, l:inflection)
-        echom 'Invalid option' | return
-    endif
-
+    " apply inflection or output error msg
+    if has_key(l:inflections, l:inflection)
         if a:0  " Invoked from Visual mode, use gv command.
             silent exe "normal! gvy"
         elseif a:type == 'line'
@@ -109,18 +106,16 @@ function! s:Inflect(type, ...)
         let l:InflectionFunction = function(l:inflections[l:inflection])
         let l:result = l:InflectionFunction(@@)

-    " set result in clipboard
-    call setreg('@', l:result, getregtype('@'))
+        " replace old text with result as literal
+        execute "normal! `[v`]c\<C-r>\<C-r>=l:result\<CR>\<Esc>"
+    else
+        echom 'Invalid option'
+    endif

-    " replace old text with result
-    normal! `[v`]p

     " restore previous state
     let @@ = l:saved_register
     call winrestview(l:winview)
-
-    " clear command line
-    echom ''
 endfunction

 " export plugin mappings
```

I also have "restore previous state" run after "Invalid option". What do you think?

**Comment by farfanoide** [comment]
really no need to modify the code, like i said, i'm still using it and it works just fine. if you provide a minimal vimrc to reproduce the error you get, we can try to fix it.

here's an example vimrc i just tested under mac os monterrey with vim 8.2 which worked just fine:
```vim
call plug#begin()
Plug 'farfanoide/inflector.vim'
call plug#end()
let g:inflector_mapping = 'gI'
```
hope that helps

**Comment by Kache** [comment]
I think I've found the reason. It seems that the intended behavior of:

```
    " set result in clipboard
    call setreg('@', l:result, getregtype('@'))
```

conflicts with `set clipboard=unnamed` (and maybe also `unnamedplus`).

Also, I think I'll instead use the simpler:

```
execute "normal! `[v`]c" . l:result
```

**Comment by Kache** [comment]
@farfanoide fyi I've found a clear repro, IMO the conflict constitutes a bug

**Comment by farfanoide** [comment]
@Kache latest commit (b224d7b9f4881222b68359e8a01f04d72237cda5) added your suggestion.
